version: '3'
services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: root
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.com
      PGADMIN_DEFAULT_PASSWORD: 1
    ports:
      - 80:80